### ISSUE TITLE
Unable to install integration

### ISSUE THREAD

**Issue by Lstick** [oxtn/ha-sql-template#1]
**System:**
Home Assistant 2023.9.2
Supervisor 2023.08.3
Operating System 10.5

### On installation
**Error #1**
_Logger: homeassistant.util.package
Source: util/package.py:108
First occurred: 12:19:19 (3 occurrences)
Last logged: 12:19:33

Unable to install package sqlalchemy==2.0.12: ERROR: Cannot install sqlalchemy==2.0.12 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.1.2 -> 23.2.1 [notice] To update, run: pip install --upgrade pip_

**Error# 2**
Logger: aiohttp.server
Source: requirements.py:289
First occurred: 12:19:33 (1 occurrences)
Last logged: 12:19:33

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 85, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 148, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 63, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 147, in post
    return await super().post(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 71, in post
    result = await self._flow_mgr.async_init(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 846, in async_init
    flow, result = await task
                   ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 864, in _async_init
    flow = await self.async_create_flow(handler, context=context, data=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 966, in async_create_flow
    handler = await _async_get_flow_handler(
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2063, in _async_get_flow_handler
    await _load_integration(hass, domain, hass_config)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2039, in _load_integration
    await async_process_deps_reqs(hass, hass_config, integration)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 420, in async_process_deps_reqs
    await requirements.async_get_integration_with_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 52, in async_get_integration_with_requirements
    return await manager.async_get_integration_with_requirements(domain)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 171, in async_get_integration_with_requirements
    await self._async_process_integration(integration, done)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 186, in _async_process_integration
    await self.async_process_requirements(
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 251, in async_process_requirements
    await self._async_process_requirements(name, missing)
  File "/usr/src/homeassistant/homeassistant/requirements.py", line 289, in _async_process_requirements
    raise RequirementsNotFound(name, list(failures))
homeassistant.requirements.RequirementsNotFound: Requirements for sql_template not found: ['sqlalchemy==2.0.12'].

**Steps I did**
Removed  "requirements": ["sqlalchemy==2.0.12"], from manifest.json. AFAIK HA already have sqlalchemy installed.
Now integration screen is starting, but any sql select * is considered as incorrect. And again and again...

**Comment by oxtn** [comment]
Thanks, for the errors I did just push a new release targeting the currently used version of SQL Alchemy (2.0.15).

Regarding the invalid message (assuming you get a validation error stating that "SQL Query invalid")... the only check that's done that'd produce that error is if your query doesn't begin with `SELECT` (case insensitive).  So, that can't be part of a template currently.  This is mainly just a basic attempt at security to prevent any potential queries that'd write against the database.

If that doesn't seem to apply to you, would you mind giving me a sample query you're trying and a screenshot with the error and I can try and track it down further.

**Comment by Lstick** [comment]
No problem with initial setup now. But query error remain the same.

**SQL query**
`SELECT weather_descr from weather_data where weather_code = {{states.sensor.sager_weather_code.state}};`


![weather_screen](https://github.com/oxtn/ha-sql-template/assets/27283031/837c3c44-97eb-4589-8849-bd12725eda70)

**Comment by oxtn** [comment]
What about if you wrap your template value in quotes like `SELECT weather_descr from weather_data where weather_code = "{{states.sensor.sager_weather_code.state}}";`

If that still doesn't work, you can enable debug logging by adding the following to your configuration.yaml (or merging the line for the component into your existing logs key, if you've already got this section):

```
logger:
  default: info
  logs:
    custom_components.sql_template: debug
```

You'll need to restart HA after that, but the next time you try to set up the integration, you should see the full SQL error in your home-assistant.log.

**Comment by oxtn** [comment]
I'm not sure that it applies to your scenario, but I did push one more update that'd fix an issue with unquoted templates during the initial setup.  Hopefully, either one of these fixes your issue.

**Comment by Lstick** [comment]
Beta2, no success with quotes .
Installed beta3. It's better, as it see correct parameter.

But now it defaults to Sqlite engine, not to MySql (my recorder)
```Logger: custom_components.sql_template.config_flow
Source: custom_components/sql_template/config_flow.py:60
Integration: SQL Template
First occurred: 17:25:37 (2 occurrences)
Last logged: 17:28:21

Execution error (sqlite3.OperationalError) no such table: weather_data [SQL: SELECT weather_descr from weather_data where weather_code = "W333";] (Background on this error at: https://sqlalche.me/e/20/e3q8)
Execution error (sqlite3.OperationalError) no such table: weather_data [SQL: SELECT weather_descr from weather_data where weather_code = W333;] (Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by oxtn** [comment]
It does default to the default SQLite path and doesn't currently fetch any customized recorder URL.

For now, you can try adding your recorder connection string in the `Database URL` configuration field.  I can take a look and see what needs to be done to pull the exact string that the `recorder` integration is using.

**Comment by Lstick** [comment]
After adding database URL it's working fine so far. Thank you for your great support!

**Comment by oxtn** [comment]
Glad to hear it and you're welcome.  Just pushed `1.0.0`, which will use the configured recorder URL when there's none provided.
